#! /bin/sh
#
# umountfs	Turn off swap and unmount all local filesystems.
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin

echo "Deactivating swap..."
swapoff -a

# We dont like to umount /sys because sysvinit.halt
# needs it to put harddiscs to standby
(cd /sys; sleep 30;) &

# We leave /proc mounted.
echo "Unmounting local filesystems..."
mount -o remount,ro /mnt/ram
umount -f -a -r

mount -o remount,ro /

: exit 0
